# All-in-one continuous integration (CI) workflow.
# Runs on all platforms (Windows, macOS, and Linux)
# for all events (pull request, release, and schedule).

name: Continuous Integration

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:

env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  PACKAGE_PREFIX: "deskflow"
  PACKAGE_PATH: ./dist
  CMAKE_CONFIGURE: "cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DSKIP_BUILD_TESTS=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=ON"

jobs:
  # Quality gate to allow PR merge, used in the branch protection rules.
  ci-passed:
    runs-on: ubuntu-latest
    needs: [main-build, test-results]
    if: always()

    steps:
      - name: Check all steps passed
        run: |
          if [[ ${{needs.main-build.result}} == 'success' && ${{needs.test-results.result}} == 'success' ]]; then
            echo "✅ CI passed" > $GITHUB_STEP_SUMMARY
          else
            exit 1
          fi

  # Summary of test results, combined from test result artifacts.
  # Runs even if the tests fail to provide a summary of the failures.
  test-results:
    needs: main-build
    if: always() && needs.main-build.result != 'skipped'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Test summary
        uses: ./.github/actions/test-summary

  lint-reuse:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  lint-clang:
    needs: [lint-reuse]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint Checker
        uses: ./.github/actions/lint-clang

  analyze-valgrind:
    needs: lint-clang
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/valgrind-analysis.yml

  main-build:
    needs: lint-clang
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.runs-on }}
    container: ${{ matrix.target.container }}
    timeout-minutes: ${{ matrix.target.timeout }}
    strategy:
      # Normally, we want to fail fast, but in this case we shouldn't since one target may
      # fail due to transient issues unrelated to the build.
      fail-fast: false

      matrix:
        target:
          - name: "windows-2022-x64"
            runs-on: "windows-2022"
            timeout: 30
            config-args: "-G Ninja"
            vcpkg-triplet: x64-windows-release
            arch: "amd64"
            qt-version: 6.10.1

          - name: "macos-arm64"
            runs-on: macos-15
            timeout: 10
            qt-version: 6.10.1
            config-args: '-DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=14 -DCMAKE_OSX_SYSROOT=/Applications/Xcode_16.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk'

          - name: "fedora-42-x86_64"
            runs-on: ubuntu-latest
            container: fedora:42
            like: "fedora"
            timeout: 20
            config-args: "-G Ninja -DCMAKE_INSTALL_PREFIX=/usr"

    steps:
      # Make sure the container has git before we do anything else
      - name: Install Git on Container
        if: ${{ matrix.target.container }}
        shell: bash
        run: |
          if [ "${{matrix.target.like}}" == "fedora" ]; then
            dnf install -y git
          fi
      # Fancy checkout gets all the tags
      # it also makes sure we can use git --describe correctly
      - name: Fancy Checkout
        uses: sithlord48/fancy-checkout@v2

      # This effectively runs `vcvarsall.bat`, etc. It's not actually installing
      # VC++ as that's already pre-installed on the Windows runner.
      - name: Setup VC++ environment
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.target.arch}}

      - name: Install dependencies
        id: get-deps
        uses: ./.github/actions/install-dependencies
        with:
          qt-version: ${{matrix.target.qt-version}}
          vcpkg-triplet: ${{matrix.target.vcpkg-triplet}}
          like: ${{ matrix.target.like }}

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: ${{env.CMAKE_CONFIGURE}} ${{ matrix.target.config-args }} ${{ steps.get-deps.outputs.vcpkg-cmake-config }} -DPACKAGE_VERSION_LABEL="${{env.DESKFLOW_PACKAGE_VERSION}}"

      - name: Build
        shell: bash
        run: cmake --build build --config Release -j8 --target package

      - name: Check for unexpected repo changes
        shell: bash
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Unexpected changes to the repo, Often caused by forgetting to commit the updated translation files"
            exit 1
          fi

      - name: Tests
        uses: ./.github/actions/run-tests
        timeout-minutes: 2
        with:
          job: ${{ matrix.target.name }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ env.PACKAGE_PREFIX }}-${{ matrix.target.name }}
          path: ${{github.workspace}}/build/deskflow[-_]*.*

  release:
    needs: ci-passed
    if: (github.ref == 'refs/heads/master') || (contains(github.ref, '/tags/v'))
    runs-on: ubuntu-latest

    steps:
      - name: Fancy Checkout
        uses: sithlord48/fancy-checkout@v2

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Generate package checksums
        id: generate_notes
        shell: bash
        run: |
          mv $GITHUB_WORKSPACE/package-*/deskflow-* .
          rm -rf $GITHUB_WORKSPACE/package-*
          echo "Build: ${{env.DESKFLOW_VERSION }}" > sums.txt
          sha256sum deskflow-* >> sums.txt

      - name: Deploy continuous
        if: (github.ref == 'refs/heads/master') && !(contains(github.ref, '/tags/v'))
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Continuous v${{env.DESKFLOW_VERSION}}"
          files: |
            deskflow-*
            sums.txt

      - name: Deploy release
        if: contains(github.ref, '/tags/v')
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            deskflow-*
            sums.txt
